app/views/admin.py
import random
import string
import re
import datetime
from flask import Flask, request, render_template, flash, redirect, url_for, session, Blueprint, send_from_directory
from passlib.hash import sha256_crypt as sha
from ..models.models import Admin, blogPosts
from app import *

admin = Blueprint('admin', __name__, url_prefix='/admin')
BLOG_IMAGE_PATH = "/assets/img/blog/"

@admin.route('/login' , methods=['POST','GET'])
def login():
    isAdmin = session.get("admin",False)
    if request.method=="POST":
        user = request.form.get("username", "default")
        password = request.form.get("password", "default")
        result = db.first_or_404(db.select(Admin).filter_by(username=user))
        invalid_credentials = False
        if result is not None:
            if result.username==user and sha.verify(password, result.password):
                session["admin"] = True
                session.permanent = True
                flash("Login Successful","success")
                return redirect(url_for("main.index"))
            else:
                invalid_credentials = True
        else:
            invalid_credentials = True
        if invalid_credentials:
            flash("Invalid Credentials, please try again!","danger")
            return redirect(url_for("admin.login"))
    else:
        return render_template('admin/login.html', admin=isAdmin)

@admin.route('/dashboard', methods=['POST','GET'])
def dashboard():
    isAdmin = session.get("admin", False)
    if request.method=="POST":
        title = request.form.get("title", "default")
        image = request.form.get("image", "default")
        content = request.form.get("content", "default")
        visible = request.form.get("visible", "off")
        slug = request.form.get("slug", "default")
        short_desc = request.form.get("description", "default")
        date = None
        print(visible)
        if visible == "on":
            date = datetime.datetime.now().strftime("%d %B, %Y")
            visible = True
        else:
            visible = False
        if len(title)==0 or len(image)==0 or len(content)==0 or len(slug)==0 or len(short_desc)==0:
            flash("Empty Fields, please try again!","danger")
        else:
            image_url = os.path.join(BLOG_IMAGE_PATH, image)
            newBlogPost = blogPosts(title=title, image=image_url, content=content, date=date, visible=visible, slug=slug, short_desc=short_desc)
            db.session.add(newBlogPost)
            db.session.commit()
            flash("Blog Post Added Successfully","success")
        return redirect(url_for("admin.dashboard"))
    if isAdmin:
        return render_template('admin/dashboard.html', admin=isAdmin)
    else:
        return redirect(url_for("admin.login"))

@admin.route('/logout')
def logout():
    session.pop("admin", False)
    flash("Logged Out","success")
    return redirect(url_for("admin.login"))

@admin.route('/delete-post/<slug>')
def delete_post(slug):
    isAdmin = session.get("admin",False)
    if isAdmin:
        db.session.query(blogPosts).filter_by(slug=slug).delete()
        db.session.commit()
        flash("Blog Post Deleted Successfully","success")
        return redirect(url_for("admin.dashboard"))
    else:
        return redirect(url_for("admin.login"))

app/views/main.py
import random
import string
import re
from flask import Flask, request, render_template, flash, redirect, url_for, session, Blueprint, send_from_directory
from passlib.hash import sha256_crypt as sha
from ..models.models import blogPosts
from app import *

main = Blueprint('main', __name__)

@main.route('/')
def index():
    admin = session.get("admin",False)
    return render_template('index.html', admin=admin)
    
@main.route('/about-us')
def about_us():
    admin = session.get("admin",False)
    return render_template('about_us.html', admin=admin)

@main.route('/contact-us', methods=['POST','GET'])
def contact_us():
    admin = session.get("admin",False)
    if request.method=="POST":
        first_name = request.form["first_name"]
        last_name = request.form["last_name"]
        contact_no = request.form["contact_no"]
        email = request.form["email"]
        message = request.form["message"]
        city = request.form["city"]

        if not contact_no.isnumeric() or len(contact_no)!=10:
            flash("Invalid Contact Number, please try again!","danger")
        elif len(message)==0:
            flash("Empty Message, please try again!","danger")
        else:
            print("Success")
            title= f"Message from Website by - {first_name} {last_name}"
            sender="sales.curezonepharma@gmail.com"
            recipients = ["info.curezonepharma@gmail.com"]
            message_html = f"Message from Website by <b>{first_name} {last_name}</b> <br> <b>Contact No:-</b> {contact_no} <br> <b>Email:-</b> {email} <br> <b>City:-</b> {city} <br> <b>Message:-</b> {message}"
            send_mail(title,sender,recipients,message_html) # Sending Mail
            flash("Query Sent Successfully","success")
        return redirect(url_for("main.contact_us"))

    return render_template('contact_us.html', admin=admin)

@main.route('/our-products')
def products():
    admin = session.get("admin",False)
    return render_template('product_page.html', admin=admin)

@main.route('/all-products')
def products_list():
    admin = session.get("admin",False)
    return render_template('product_list.html', admin=admin)

@app.route('/sitemap.xml')
def sitemap_from_root():
    return send_from_directory(app.static_folder, request.path[1:])

@app.route('/robots.txt')
def robots_txt_from_root():
    return send_from_directory(app.static_folder, request.path[1:])

@main.route('/blog')
def blog():
    admin = session.get("admin",False)
    posts = db.session.query(blogPosts).filter_by(visible=True).order_by(blogPosts.date).all()
    print(posts)
    return render_template('blog.html', **locals())

@main.route('/blog-post/<slug>')
def blog_post(slug):
    admin = session.get("admin",False)
    post = db.session.execute(db.select(blogPosts).filter_by(slug=slug)).scalar()
    if post is None:
        flash("Blog Post Not Found","warning")
        return redirect(url_for("main.blog"))
    return render_template('blog_post.html', **locals())

# @main.route('/populate-admin')
# def populate_admin():
#     admin = Admin("username", sha.hash("password"))
#     db.session.add(admin)
#     db.session.commit()
#     return "Admin Populated"

app/templates/about-us.html
{% extends 'base_template.html' %}

{% block body_class %}
  about-us
{% endblock %}

{% block main %}

<div class="page-header page-header-small" style="background-image: url('assets/img/medicines_bg.jpg');">
  <div class="filter"></div>
  <div class="content-center">
      <div class="container">
          <h1>Hello, <br /> We are Curezone Pharma!</h1>
          <h3>Let us tell you more about what we do.</h3>
      </div>
  </div>
</div>
<div class="main">
  <div class="section">
      <div class="container">
          <h3 class="title-uppercase">We build great products.</h3>
          <p>Curezone is a leading PCD pharma company that provides high-quality pharmaceuticals and healthcare Products to people across India. 
              With a focus on innovation and the use of cutting-edge technology, Curezone is committed to improving the lives of people and making healthcare accessible to everyone.
          </p>
          <h3 class="title-uppercase">We <i class="fa fa-heart heart"></i>&nbsp; what we do.</h3>
          <p>The company boasts a wide range of products that covers all major therapeutic segments and is backed by a team of experienced professionals who are dedicated to ensuring the highest standards of quality and customer satisfaction. 
              With a strong network of distributors and a well-established reputation in the industry, Curezone is poised for continued growth and success in the years to come. 
          </p>
      </div>
  </div>
</div>

{% endblock %}

app/templates/about_us.html
{% extends 'base_template.html' %}

{% block body_class %}
  about-us
{% endblock %}

{% block main %}

<div class="page-header page-header-small" style="background-image: url('/assets/img/medicines_bg.jpg');">
  <div class="filter"></div>
  <div class="content-center">
      <div class="container">
          <h1>Hello, <br /> We are Curezone Pharma!</h1>
          <h3>Let us tell you more about what we do.</h3>
      </div>
  </div>
</div>
<div class="main">
  <div class="section">
      <div class="container">
          <h3 class="title-uppercase">We build great products.</h3>
          <p>Curezone is a leading PCD pharma company that provides high-quality pharmaceuticals and healthcare Products to people across India. 
              With a focus on innovation and the use of cutting-edge technology, Curezone is committed to improving the lives of people and making healthcare accessible to everyone.
          </p>
          <h3 class="title-uppercase">We <i class="fa fa-heart heart"></i>&nbsp; what we do.</h3>
          <p>The company boasts a wide range of products that covers all major therapeutic segments and is backed by a team of experienced professionals who are dedicated to ensuring the highest standards of quality and customer satisfaction. 
              With a strong network of distributors and a well-established reputation in the industry, Curezone is poised for continued growth and success in the years to come. 
          </p>
      </div>
  </div>
</div>

{% endblock %}

app/templates/blog.html
{% extends 'base_template.html' %}

{% block body_class %}
  blog
{% endblock %}

{% block main %}

<div class="page-header page-header-small" style="background-image: url('/assets/img/blog-bg.jpg');">
  <div class="filter"></div>
  <div class="content-center">
      <div class="container">
          <h1>Latest News & Updates</h1>
          <h3>Stay informed with our recent developments.</h3>
      </div>
  </div>
</div>
<div class="main">
  <div class="section">
    <div class="blog-4">
      <div class="container">
        {% for post in posts %}
          {% if loop.index0 is divisibleby 2 %}
            <div class="row">
          {% endif %}
          <div class="col-md-6">
            <div class="card card-plain card-blog text-center">
              <div class="card-image">
                <img class="img img-raised" src="{{ post.image }}"/>
              </div>
              <div class="card-body">
                <h3 class="card-title">
                  <a href="{{ url_for('main.blog_post', slug=post.slug)}}"> {{ post.title }}</a>
                </h3>
                <p class="card-description">
                  {{ post.short_desc }}
                </p>
              </br>
                <div class="row d-flex flex-wrap align-items-center">
                  <div class="col-md-6">
                    <a href="{{ url_for('main.blog_post', slug=post.slug)}}" class="btn btn-round"> Read More</a>
                  </div>
                  <div class="col-md-6 mr-auto" style="font-size: medium;">
                    <i class="fa fa-calendar" aria-hidden="true"></i> {{ post.date }}
                  </div>
                </div>
                {% if admin %}
                  <a href="{{ url_for('admin.delete_post', slug=post.slug)}}" class="btn btn-error btn-round"> Delete Post </a>
                {% endif %}
              </div>
            </div>
          </div>
          {% if loop.index0 is not divisibleby 2 %}
            </div>
          {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

app/templates/blog_post.html
{% extends "base_template.html" %}

{% block body_class %}
  blog-post
{% endblock %}

{% block main %}
  <div class="page-header page-header-small" style="background-image: url('/assets/img/blog-bg.jpg');">
    <div class="filter"></div>
    <div class="content-center">
        <div class="container">
            <h2>{{ post.title }}</h2>
        </div>
    </div>
  </div>
  <div class="main">
    <div class="section section-white">
      <div class="container">
        <div class="row">
          <div class="col-md-10 ml-auto mr-auto">
            <div class="text-center">
              <h5 class="title-uppercase">Posted on {{ post.date }}</h5>
            </div>
          </div>
          <div class="col-md-8 ml-auto mr-auto">
            <img class="img img-raised img-fluid" src="{{ post.image }}"/>
            </br></br>
            <div class="article-content">
              {{ post.content|safe }}
            </div>
            <br />
            <div class="article-footer">
              <div class="container">
                <div class="row"  style="text-align: right;">
                  <div class="col-md-4 ml-auto">
                    <div class="sharing">
                      <h5>Spread the word</h5>
                        <i class="fa fa-2x fa-twitter"></i> &nbsp;&nbsp;&nbsp;
                        <i class="fa fa-2x fa-facebook"> </i> &nbsp;
                        <i class="fa fa-2x fa-google"> </i>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/contact-us.html
{% extends 'base_template.html' %}

{% block body_class %}
  contact-page
{% endblock %}

{% block main %}
<div class="main">
    <div class="contactus-1 section-black" style="background-image: url('assets/img/contact_us_1.jpg'); background-size: cover;">
        <div class="container">
            <br><br><br>
            <div class="row">
                <div class="col-md-10 ml-auto mr-auto">
                    <div class="card card-contact no-transition">
                      <h3 class="card-title text-center"><b>Contact Us</b></h3>
                        <div class="row">
                            <div class="col-md-5 ml-auto">
                                <div class="card-body">
                                    <div class="info info-horizontal">
                                        <div class="icon icon-info">
                                            <i class="nc-icon nc-pin-3" aria-hidden="true"></i>
                                        </div>
                                        <div class="description">
                                          <h4 class="info-title"><b>Find us at the office</b></h4>
                                            <p><b> Gupta Complex, First Floor,<br>
                                                Nanhera Road, Kuldeep Nagar,<br>
                                                Ambala Cantt, <br>
                                                Haryana<br>
                                                India - 133004
                                            </b></p>
                                        </div>
                                    </div>
                                    <div class="info info-horizontal">
                                        <div class="icon icon-danger">
                                            <i class="nc-icon nc-badge" aria-hidden="true"></i>
                                        </div>
                                        <div class="description">
                                          <h4 class="info-title"><b>Give us a ring</b></h4>
                                            <p><b> +91-7056560081,<br>
                                                   +91-7056560082
                                            </b></p>
                                        </div>
                                    </div>
                                    <div class="info info-horizontal">
                                        <div class="icon icon-success">
                                            <i class="nc-icon nc-email-85" aria-hidden="true"></i>
                                        </div>
                                        <div class="description">
                                          <h4 class="info-title"><b>Drop us a email at</b></h4>
                                            <p><b> info.curezonepharma@gmail.com,<br>
                                              sales.curezonepharma@gmail.com
                                          </b></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-5 mr-auto">
                                <form role="form" id="contact-form" method="post">
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group label-floating">
                                                  <label class="control-label"><b>First name</b></label>
                                                    <input type="text" name="first_name" class="form-control" placeholder="First Name">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group label-floating">
                                                  <label class="control-label"><b>Last name</b></label>
                                                    <input type="text" name="last_name" class="form-control" placeholder="Last Name">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group label-floating">
                                          <label class="control-label"><b>Contact No.</b></label>
                                            <input type="text" name="contact_no" class="form-control" placeholder="Contact Number" />
                                        </div>
                                        <div class="form-group label-floating">
                                            <label class="control-label"><b>City</b></label>
                                              <input type="text" name="city" class="form-control" placeholder="City" />
                                          </div>
                                        <div class="form-group label-floating">
                                          <label class="control-label"><b>Email address</b></label>
                                            <input type="email" name="email" class="form-control" placeholder="Email" />
                                        </div>
                                        <div class="form-group label-floating">
                                          <label class="control-label"><b>Your message</b></label>
                                            <textarea name="message" class="form-control" id="message" rows="6" placeholder="Message"></textarea>
                                        </div>
                                        <div class="row justify-content-center">
                                            <div class="col-md-6">
                                                <button type="submit" class="btn btn-primary pull-right">Send Message</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13774.939400169611!2d76.8438292668668!3d30.330058946493523!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390fb59ca7b73449%3A0x86ea27b96e9f0752!2sCurezone%20Pharma!5e0!3m2!1sen!2suk!4v1686611705480!5m2!1sen!2suk" width="100%" height="400px" style="border:0;" allowfullscreen loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>


{% endblock %}

app/templates/contact_us.html
{% extends 'base_template.html' %}

{% block body_class %}
  contact-page
{% endblock %}

{% block main %}
<div class="main">
    <div class="contactus-1 section-black" style="background-image: url('/assets/img/contact_us_1.jpg'); background-size: cover;">
        <div class="container">
            <br><br><br>
            <div class="row">
                <div class="col-md-10 ml-auto mr-auto">
                    <div class="card card-contact no-transition">
                      <h3 class="card-title text-center"><b>Contact Us</b></h3>
                        <div class="row">
                            <div class="col-md-5 ml-auto">
                                <div class="card-body">
                                    <div class="info info-horizontal">
                                        <div class="icon icon-info">
                                            <i class="nc-icon nc-pin-3" aria-hidden="true"></i>
                                        </div>
                                        <div class="description">
                                          <h4 class="info-title"><b>Find us at the office</b></h4>
                                            <p><b> Gupta Complex, First Floor,<br>
                                                Nanhera Road, Kuldeep Nagar,<br>
                                                Ambala Cantt, <br>
                                                Haryana<br>
                                                India - 133004
                                            </b></p>
                                        </div>
                                    </div>
                                    <div class="info info-horizontal">
                                        <div class="icon icon-danger">
                                            <i class="nc-icon nc-badge" aria-hidden="true"></i>
                                        </div>
                                        <div class="description">
                                          <h4 class="info-title"><b>Give us a ring</b></h4>
                                            <p><b> +91-7056560081,<br>
                                                   +91-7056560082
                                            </b></p>
                                        </div>
                                    </div>
                                    <div class="info info-horizontal">
                                        <div class="icon icon-success">
                                            <i class="nc-icon nc-email-85" aria-hidden="true"></i>
                                        </div>
                                        <div class="description">
                                          <h4 class="info-title"><b>Drop us a email at</b></h4>
                                            <p><b> info.curezonepharma@gmail.com,<br>
                                              sales.curezonepharma@gmail.com
                                          </b></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-5 mr-auto">
                                <form role="form" id="contact-form" method="post">
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group label-floating">
                                                  <label class="control-label"><b>First name</b></label>
                                                    <input type="text" name="first_name" class="form-control" placeholder="First Name">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group label-floating">
                                                  <label class="control-label"><b>Last name</b></label>
                                                    <input type="text" name="last_name" class="form-control" placeholder="Last Name">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group label-floating">
                                          <label class="control-label"><b>Contact No.</b></label>
                                            <input type="text" name="contact_no" class="form-control" placeholder="Contact Number" />
                                        </div>
                                        <div class="form-group label-floating">
                                            <label class="control-label"><b>City</b></label>
                                              <input type="text" name="city" class="form-control" placeholder="City" />
                                          </div>
                                        <div class="form-group label-floating">
                                          <label class="control-label"><b>Email address</b></label>
                                            <input type="email" name="email" class="form-control" placeholder="Email" />
                                        </div>
                                        <div class="form-group label-floating">
                                          <label class="control-label"><b>Your message</b></label>
                                            <textarea name="message" class="form-control" id="message" rows="6" placeholder="Message"></textarea>
                                        </div>
                                        <div class="row justify-content-center">
                                            <div class="col-md-6">
                                                <button type="submit" class="btn btn-primary pull-right">Send Message</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13774.939400169611!2d76.8438292668668!3d30.330058946493523!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390fb59ca7b73449%3A0x86ea27b96e9f0752!2sCurezone%20Pharma!5e0!3m2!1sen!2suk!4v1686611705480!5m2!1sen!2suk" width="100%" height="400px" style="border:0;" allowfullscreen loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>


{% endblock %}